config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  # ユーザー
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  resources :users, only: [:show, :edit, :update] do
  end

  # コーディネート
  resources :articles do
    get 'rank', on: :collection
    get '/gender/:gender', to: 'articles#index', as: 'gender_index', on: :collection
  end

  # アイテム
  resources :gears, only: [:index] do
    get '/search_article', to: 'gears#search_article', as: 'search_article', on: :collection
    get '/narrow_down', to: 'gears#search_gear', as: 'narrow_down', on: :collection
    # post '/rakuten_search', to: 'gears#rakuten_search', as: 'rakuten_search', on: :collection
    post '/rakuten_search', to: 'gears#rakuten_search', as: 'rakuten_search'
  end

  # いいね
  resources :likes, only: [:create, :destroy]
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :bigint           not null, primary key
#  photo       :string(255)
#  comment     :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          not null
#  likes_count :integer
#

class Article < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :gears, inverse_of: :article
  accepts_nested_attributes_for :gears, allow_destroy: true
  has_many :likes, dependent: :destroy
  default_scope -> { order(created_at: :desc) }

  validates :photo, presence: true
  validates :comment, presence: true, length: { maximum: 200 }
  validate :kind_uniq

  scope :change_gender, ->(gender) { joins(:user).where('gender = ?', gender) }
  scope :rank, -> { find(Like.group(:article_id).order('count(article_id) desc').pluck(:article_id)) }
  scope :search, ->(keyword) { includes(:gears).where('gears.name LIKE ?', "%#{keyword}%").references(:gears) }

  def kind_uniq
    kinds = []
    gears.each do |gear|
      kinds << gear.kind
    end

    errors.add(:gear, 'アイテムの種類は最大1種類ずつのみ登録可能です。') if kinds.size != kinds.uniq.size
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :update]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @articles = if params[:gender].present?
                  Article.change_gender(params[:gender])
                else
                  Article.all
                end
  end

  def show
    @article = Article.find(params[:id])
    @gears = @article.gears
  end

  def new
    @article = Article.new
    @article.gears.build
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to articles_path, notice: '記事を登録しました。'
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
    @article.gears.build
  end

  def update
    @article = Article.find(params[:id])
    @article.user_id = current_user.id

    @article.photo = default_url if @article.photo.nil?

    if @article.update(article_params)
      redirect_to articles_path, notice: '記事を更新しました。'
    else
      render :edit
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to articles_path, notice: '記事を削除しました。'
  end

  def rank
    @articles = Article.rank
  end

  private

  def article_params
    params.require(:article).permit(
      :photo,
      :comment,
      gears_attributes: [
        :id,
        :gear_image,
        :name,
        :brand,
        :kind,
        :model_year,
        :_destroy
      ]
    )
  end

  def correct_user
    @article = current_user.articles.find_by(id: params[:id])
    redirect_to(root_path) unless @article
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.slim
- if articles.present?
  .container-fluid
    .row
      - articles.each do |article|
        .col-md-4
          .card.mb-4
            = link_to image_tag(article.photo.thumb.url, width: "100%", height: "100%"), article_path(article), class: "card-img-top", id: "thmb"
            .card-body
              .media
                .circle-image
                  - if article.user.profile_image?
                    = image_tag(article.user.profile_image.to_s, class: "mr-3")
                  - else
                    = image_tag("default.jpg", class: "mr-3")
                .media-body
                  = article.user.name
                  p.card-text
                    small.text-muted
                      | #{article.user.height}cm
            .card-footer id="like-btn-#{article.id}"
              == render partial: "likes/like", locals: { article: article }
- else
  h1 投稿された記事が見つかりません。

app/views/articles/_form.html.slim
.container
    = nested_form_for article, local: true do |f|
        = render 'layouts/error', { object: f.object}

        .form-group
          .row
            .col-4
              = f.label :photo
            .col-8
              - if article.photo?
                = image_tag(article.photo.url, id: 'img_prev')
              - else
                = image_tag('nofile.jpg', id: 'img_prev')
              = f.file_field :photo, class: "form-control-file", id: "image-file"
        .form-group
            = f.label :comment
            = f.text_area :comment, class: "form-control"
        .row
          .col-10
            h2
              | アイテム詳細
        = f.fields_for :gears do |g|
          .item
            .row
              .col-6
                .form-group
                  = g.label :gear_image
                  - if g.object.gear_image?
                    = image_tag(g.object.gear_image.url, id: 'preview', class: 'gear_image')
                  - else
                    = image_tag('nofile.jpg', id: 'preview', class: 'gear_image')
                  = g.file_field :gear_image, class: "form-control-file image_preview"
              .col-6
                .form-group
                  = g.label :name
                  = g.text_field :name, class: "form-control"
                .form-group
                  = g.label :brand
                  = g.text_field :brand, class: "form-control"
                .form-group
                  = g.label :kind
                  = g.select :kind, gear_type_list, { include_blank: true }, class: "form-control"
                .form-group
                  = g.label :model_year
                  = g.text_field :model_year, class: "form-control"
                = g.link_to_remove '削除', class: 'btn btn-danger'
        = f.link_to_add '追加', :gears, class: 'btn btn-primary', id: 'add-form'

        .actions
          = f.submit nil, class: 'btn btn-primary'

app/views/articles/edit.html.slim
h1 class="row justify-content-center"
    | コーディネート編集

= render 'form', article: @article

app/views/articles/index.html.slim
h2 class="text-center"
  | コーディネート

ul.nav.nav-tabs.nav-fill
  li.nav-item
    = link_to  "ALL", articles_path, class: "nav-link #{('active' if current_page?(articles_path))}"
  li.nav-item
    = link_to  "MEN", gender_index_articles_path(gender: 1), class: "nav-link #{('active' if current_page?('/articles/gender/1'))}"
  li.nav-item
    = link_to  "WOMEN", gender_index_articles_path(gender: 2), class: "nav-link #{('active' if current_page?('/articles/gender/2'))}"

= render 'articles/article', articles: @articles

app/views/articles/new.html.slim
h1 class="row justify-content-center"
    | コーディネート投稿

= render 'form', article: @article

app/views/articles/rank.html.slim
h2 class="text-center"
  | いいねランキング

== render 'article', articles: @articles

app/views/articles/show.html.slim
.row
  .col-md-3
    = render 'shared/profile_image', user: @article.user
  .col-md-9
    table.table
      tbody
        tr
          th ユーザー名
          td = @article.user.name
        tr
          th 性別
          - if @article.user.gender == 1
            td MEN
          - else
            td WOMEN
        tr
          th 身長
          td = @article.user.height

.row
  .col-md-6
    h2
        | コーディネート
  .col-md-6
    .float-right
      - if user_signed_in? && current_user.id == @article.user.id
        button.edit-btn
          = link_to edit_article_path(@article) do
            = icon("fas", "edit fa-2x")
        button.delete-btn
          = link_to @article, method: :delete, data: { confirm: "記事を削除します。よろしいですか？" } do
            = icon("fas", "trash-alt fa-2x")

.card.mb-3
    .row.no-gutters
        .col-md-4.my-auto
            = image_tag(@article.photo.url, class: "card-img")
        .col-md-8
            .card-body
                = @article.comment

h2
    | 着用アイテム

= render 'gears/gear', gears: @gears