config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  # ユーザー
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  resources :users, only: [:show, :edit, :update] do
  end

  # コーディネート
  resources :articles do
    get 'rank', on: :collection
    get '/gender/:gender', to: 'articles#index', as: 'gender_index', on: :collection
  end

  # アイテム
  resources :gears, only: [:index] do
    get '/search_article', to: 'gears#search_article', as: 'search_article', on: :collection
    get '/narrow_down', to: 'gears#search_gear', as: 'narrow_down', on: :collection
    # post '/rakuten_search', to: 'gears#rakuten_search', as: 'rakuten_search', on: :collection
    post '/rakuten_search', to: 'gears#rakuten_search', as: 'rakuten_search'
  end

  # いいね
  resources :likes, only: [:create, :destroy]
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :bigint           not null, primary key
#  user_id    :integer
#  article_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article, counter_cache: :likes_count
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_id_name

  def create
    @like = current_user.likes.create!(article_id: @article.id)
  end

  def destroy
    @like = current_user.likes.find_by(article_id: params[:id])
    @like.destroy!
  end

  private

  def set_id_name
    @article = Article.find(params[:id])
    @id_name = "#like-btn-#{@article.id}"
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.slim
- if user_signed_in?
  - if current_user.likes.find_by(article_id: article.id)
    = form_with url: like_path(article.id), method: :delete, remote: true do |f|
      = button_tag type: "submit", class: "like-btn flowbtn12 fl_pf12" do
        = icon("fas", "heart")
        = article.likes.count
  - else
    = form_with url: likes_path, remote: true do |f|
      = hidden_field_tag :id, article.id
      = button_tag type: "submit", class: "like-btn flowbtn11 fl_pf11" do
        = icon("fas", "heart")
        = article.likes.count


- else
  .like-btn.flowbtn11.fl_pf11
  = icon("fas", "heart")
	= article.likes.count

app/views/likes/create.js.erb
$("<%= @id_name =%>").html("<%= escape_javascript(render partial: 'likes/like', locals: {article: @article}) %>");

app/views/likes/destroy.js.erb
$("<%= @id_name =%>").html("<%= escape_javascript(render partial: 'likes/like', locals: {article: @article}) %>");