config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  # ユーザー
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  resources :users, only: [:show, :edit, :update] do
  end

  # コーディネート
  resources :articles do
    get 'rank', on: :collection
    get '/gender/:gender', to: 'articles#index', as: 'gender_index', on: :collection
  end

  # アイテム
  resources :gears, only: [:index] do
    get '/search_article', to: 'gears#search_article', as: 'search_article', on: :collection
    get '/narrow_down', to: 'gears#search_gear', as: 'narrow_down', on: :collection
    # post '/rakuten_search', to: 'gears#rakuten_search', as: 'rakuten_search', on: :collection
    post '/rakuten_search', to: 'gears#rakuten_search', as: 'rakuten_search'
  end

  # いいね
  resources :likes, only: [:create, :destroy]
end

app/models/gear.rb
# == Schema Information
#
# Table name: gears
#
#  id         :bigint           not null, primary key
#  article_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  gear_image :string(255)
#  name       :string(255)
#  kind       :string(255)
#  brand      :string(255)
#  model_year :integer
#

class Gear < ApplicationRecord
  mount_uploader :gear_image, GearImageUploader
  belongs_to :article

  validates :name, presence: true, length: { maximum: 30 }
  validates :brand, presence: true
  validates :kind, presence: true
  validates :model_year, presence: true,
                         format: { with: /\A20\d{2}/, message: 'は「20XX」の形式で入力してください。' }

  scope :narrow_down_name, ->(name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :narrow_down_brand, ->(brand) { where('brand = ?', brand) if brand.present? }
  scope :narrow_down_kind, ->(kind) { where('kind = ?', kind) if kind.present? }

  scope :search, ->(gear_search_params) do
    return if gear_search_params.blank?

    narrow_down_name(gear_search_params[:name])
      .narrow_down_brand(gear_search_params[:brand])
      .narrow_down_kind(gear_search_params[:kind])
  end

  def get_search_keyword
    keyword = name + ' '
    keyword << brand + ' '
    keyword << kind + ' '
    keyword << model_year.to_s
  end
end

app/controllers/gears_controller.rb
require 'gear.rb'

class GearsController < ApplicationController
  before_action :narrow_down_list, only: [:index, :search_gear]

  def index
    @gears = Gear.all
  end

  def search_gear
    @gears = Gear.search(gear_search_params)
    render action: :index
  end

  def search_article
    keyword = params[:search]
    @articles = Article.search(keyword)
    render 'articles/index'
  end

  def rakuten_search
    gear = Gear.find(params[:gear_id])
    keyword = gear.get_search_keyword
    @items = RakutenWebService::Ichiba::Item.search(keyword: keyword)
  end

  private

  def gear_search_params
    params.require(:gear).permit(:name, :brand, :kind, :search)
  end

  def narrow_down_list
    @brands = []
    @kinds = []

    Gear.all.each do |gear|
      @brands << gear.brand
      @kinds << gear.kind
    end
  end
end

app/helpers/gears_helper.rb
module GearsHelper
  def gear_type_list
    %w[ヘルメット ゴーグル グローブ ジャケット パンツ パーカー フリース]
  end
end

app/views/gears/_gear.html.slim
.container
  .row
    - gears.each do |gear|
      .col-md-4
        .card.md-4
          - if gear.gear_image?
            = image_tag(gear.gear_image.url, class: "card-img")
          - else
            = image_tag("nofile.jpg", class: "card-img")
          .card-body
            table.table
              tbody
                tr
                  th アイテム名
                  td = gear.name
                tr
                  th ブランド
                  td = gear.brand
                tr
                  th 種類
                  td = gear.kind
                tr
                  th モデル年式
                  td = gear.model_year
          .card-footer
            .row
              .col-md-6
                = form_with url: search_article_gears_path, method: :get, local: true do |f|
                  = f.hidden_field :search, :value => "#{gear.name}"
                  = f.submit 'コーデを検索', class: 'btn btn-primary'
              .col-md-6
                = form_with url: gear_rakuten_search_path(gear.id), method: :post, local: true do |f|
                  = f.submit '楽天で検索', class: 'btn btn-primary'

app/views/gears/index.html.slim
.display-4 class="text-center"
  | アイテム一覧

.row
  .col-md-12
    .container
      h3 アイテム検索
      .jumbotron
        = form_with model: Gear.new, url: narrow_down_gears_path, method: :get, local: true do |f|
          = f.label 'キーワード検索'
          = f.text_field :name, placeholder: 'アイテム名を入力してください', class: 'form-control'
          .form-group
            = f.label :brand
            = f.select :brand, @brands.each { |brand| brand }, { include_blank: true }, class: "form-control"
          .form-group
            = f.label :kind
            = f.select :kind, gear_type_list, { include_blank: true }, class: "form-control"
          = f.submit '検索', class: 'btn btn-primary'

    = render 'gears/gear', gears: @gears

app/views/gears/rakuten_search.html.slim
.display-4 class="text-center"
  | 楽天市場検索結果

- if @items.count > 0
    table.table
      tbody
        tr
          th アイテム画像
          th アイテム名
          th 値段
        - @items.each do |item|
          tr
            td= link_to image_tag(item['mediumImageUrls'][0]), item['itemUrl'], target: :_blank
            td= item['itemName']
            td
              | ¥
              = item['itemPrice']

- else
  h2.text-center 商品が見つかりませんでした。