config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  # ユーザー
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  resources :users, only: [:show, :edit, :update] do
  end

  # コーディネート
  resources :articles do
    get 'rank', on: :collection
    get '/gender/:gender', to: 'articles#index', as: 'gender_index', on: :collection
  end

  # アイテム
  resources :gears, only: [:index] do
    get '/search_article', to: 'gears#search_article', as: 'search_article', on: :collection
    get '/narrow_down', to: 'gears#search_gear', as: 'narrow_down', on: :collection
    # post '/rakuten_search', to: 'gears#rakuten_search', as: 'rakuten_search', on: :collection
    post '/rakuten_search', to: 'gears#rakuten_search', as: 'rakuten_search'
  end

  # いいね
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_error.html.slim
- if object.errors.any?
  .alert.alert-danger
    - object.errors.full_messages.each do |msg|
      li = msg

app/views/layouts/_flash.html.slim
- if flash.notice
  .notice.alert.alert-success 
    p = flash.notice

app/views/layouts/_footer.html.slim
.container
  p
    a href="#" ガイドライン
    |・
    a href="#" プライバシーポリシー
    -if user_signed_in?
      |・
      = link_to 'マイページ', user_path(id: current_user.id)
                    
.footer_bar
  p copyright (C) 2019 wear_coodinate all rights reserved.

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-md.navbar-bg-dark
    = link_to 'WEAR_COODINATE', root_path, class: "navbar-brand"

    .collapse.navbar-collapse#navbarNav
        ul.navbar-nav.ml-auto
                li.nav-item.dropdown
                    a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                        = icon("fas", "tshirt")
                        | コーディネート
                    .dropdown-menu
                        = link_to 'コーディネート集', articles_path, class: 'nav-link'
                        = link_to 'いいねランキング', rank_articles_path, class: 'nav-link'

                li.nav-item.dropdown
                    a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                        = icon("fas", "mitten")
                        | アイテム
                    .dropdown-menu
                        = link_to 'アイテムリスト', gears_path, class: 'nav-link'

                - if user_signed_in?
                    li.nav-item
                        = link_to new_article_path, class: 'nav-link' do
                            = icon("far", "image")
                            |  新規投稿

                    li.nav-item.dropdown
                        a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                            = icon("fas", "user")
                            |  #{current_user.name}
                        .dropdown-menu
                            = link_to "マイページ", user_path(id: current_user.id), class: "dropdown-item"
                            = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item"
                - else
                    li.nav-item
                        = link_to 'ログイン', new_user_session_path, class: "nav-link"
                    li.nav-item
                        = link_to 'ユーザー登録', new_user_registration_path, class: "nav-link"
                        

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    meta charset="UTF-8"/
    title
      | WearCoodinate
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    header
      == render 'layouts/header'

    .container
      main
        == render 'layouts/flash'
        == yield

    footer
      == render 'layouts/footer'